server:
  port: 8188


service-url:
  user-service: http://localhost:8189
  order-service: http://localhost:8190



spring:
  application:
    name: api-gateway
  profiles:
    active: predicate
#    active: filter

#  cloud:
#    gateway:
#      routes:
#        - id: user #\u8DEF\u7531\u7684ID
#          uri: ${service-url.user-service}/user/{id} #\u5339\u914D\u540E\u8DEF\u7531\u5730\u5740
#          predicates: # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
#            - Path=/user/{id}
#
#        - id: order #\u8DEF\u7531\u7684ID
#          uri: ${service-url.order-service}/order/{id} #\u5339\u914D\u540E\u8DEF\u7531\u5730\u5740
#          predicates: # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
#            - Path=/order/{id}


